language: php
dist: bionic
sudo: required
group: edge
env:
  global:
  - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"
branches:
  only:
  - develop
  - feature/tests
services:
- mysql
- postgresql
matrix:
  fast_finish: true
  include:
  - php: 7.3
    env: DB=mysql
  - php: 7.3
    env: DB=pgsql
  - php: 7.2
    env: DB=mysql
  - php: 7.2
    env: DB=pgsql
  - php: 7.1
    env: TASK_TESTS_COVERAGE=1 DB=mysql
  - php: 7.1
    env: TASK_TESTS_COVERAGE=1 DB=pgsql
cache:
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.npm"
addons:
  postgresql: '9.6'
install:
- |
  if [[ $TASK_TESTS_COVERAGE != 1 ]]; then
    # disable xdebug for performance reasons when code coverage is not needed.
    phpenv config-rm xdebug.ini || echo "xdebug is not installed"
  fi

  # install composer dependencies
  export PATH="$HOME/.composer/vendor/bin:$PATH"
  composer validate
  travis_retry composer install $DEFAULT_COMPOSER_FLAGS
before_script:
- |
  # show some version and environment information
  php --version
  composer --version
  php -r "echo INTL_ICU_VERSION . \"\n\";"
  php -r "echo INTL_ICU_DATA_VERSION . \"\n\";"
  psql --version
  mysql --version
  sudo mysql_upgrade || echo "MySQL is already up to date"
- travis_retry mysql -e 'CREATE DATABASE `craft-test`;';
- mysql -e "SET GLOBAL sql_mode = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';";
- psql -U postgres -c 'CREATE DATABASE "craft-test";';
- pear config-set preferred_state beta
- pecl channel-update pecl.php.net
- yes | pecl install imagick
- cp tests/.env.example.$DB tests/.env
script:
- |
  if [[ $TASK_TESTS_COVERAGE != 1 ]]; then
    vendor/bin/codecept run unit,functional
  else
    mkdir -p build/logs
    vendor/bin/codecept run unit,functional --coverage-xml coverage.xml;
  fi
after_script:
- |
  if [ $TASK_TESTS_COVERAGE == 1 ]; then
    bash <(curl -s https://codecov.io/bash)
  fi
notifications:
  slack:
    rooms:
      - secure: "3WDFBPYRUyxQZ+I3iCgPotykc0Fbl/bsSQVigOd/RP5QHzw6ex/6Ti+vD0KZgxc+Dj1tmqkdIOMge2OlH4cE2UgyWcTrOn8RpabNKHEXBIQv5+GmNkiw+3D9n9lHOxeQOWbASDRQDYW9Pv3v0tQ/nFgzDmf8Cjr4cxexFhKV+Eo9og2ajqL0iRaXu+lmE3UaShA9VxOZswOkAgd1ZStH0AdbpaGcJxk7D+46kh6w9cyNtJHxJcvmi1lK8ZJxwCkUnxqMzVaicwpvHzW39FJTW+GK5puj7n6q0nuHLSE0q3Nf3LcCW9yWpd0Ykhm/w+F3+fg0Q5ztV9YVnlnazQpiEkfC1JJ0Qy6jVwTtUqoLOkGWhoXI4gPujL5QYJ7uIqLzo/a0ubhoJ5ZpfVlM9GYHX2bTLBvjUFONNiap5Ms+OuwKOEDoysVdhbcmR05CKo1yXXHmD6AO4tnVth8iWxJ7JQFjjPaOd7/ysVKhKgB/92oCskV02ElJbagliD/TwPw8+afjKcM8ilaBv5S6u4dHwX4dEoKQqwsuZ6zrjpB1KCTQ0SLARiqoomq0hxC5oibhVyZwaS+8zzzOzVhnTpR9ZQ406Ici+Rk/oayP438qZ2fon7cq1IWtc7Gyt+jERZqGQQd59XMG7gDRKcD9Ip/Jm7Y32xmJXNNlGybognqUomc="
  email:
    recipients:
    - brad@craftcms.com
    - brandon@craftcms.com
