"project_identifier" : "craft-cms"
"api_key_env" : CROWDIN_API_KEY
"base_path" : "/src/translations"
"preserve_hierarchy": true

#
# Files configuration
#
files: [
{
  #
  # Source files filter
  # e.g. "/resources/en/*.json"
  #
  "source" : "/en/app.php",

  #
  # where translations live
  # e.g. "/resources/%two_letters_code%/%original_file_name%"
  #
  "translation" : "/%two_letters_code%/app.php",

  #
  # files or directories for ignore
  # e.g. ["/**/?.txt", "/**/[0-9].txt", "/**/*\?*.txt"]
  #
  # "ignore" : ["/en/app.php"],

  #
  # File type
  # e.g. "json"
  #
  "type" : "php",

  #
  # The parameter "update_option" is optional. If it is not set, translations for changed strings will be lost. Useful for typo fixes and minor changes in source strings.
  # e.g. "update_as_unapproved" or "update_without_changes"
  #
  #"update_option" : "",
  #
}
]